# Generated by Django 3.2.24 on 2024-02-28 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='cod9XSZG5B52PM32V178', editable=False, help_text='codigo', max_length=16, null=True, unique=True)),
                ('nome', models.CharField(max_length=225, verbose_name='nome')),
                ('descricao', models.CharField(max_length=225, verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='CursoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
            ],
        ),
    ]
