# Generated by Django 3.2.24 on 2024-02-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(default='matED06JI95AEOY3DX7W', editable=False, help_text='matricula', max_length=16, null=True, unique=True)),
                ('nome', models.CharField(max_length=225, verbose_name='nome')),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('data_de_nascimento', models.DateField(verbose_name='data de nascimento')),
            ],
        ),
    ]
